##########################################
## https://github.com/daycat/proxypool ###
##########################################


# your domain
domain: 
port:                 # default 12580

# source list file
source-files:
  # use local file
  # - ./source.yaml
  # use web file
  - https://raw.githubusercontent.com/yu-steven/openit/patch/sub/source.yaml
