name: Nodes
on: 
  schedule:
    - cron: '*/32 0-14 * * *'
    - cron: '*/51 14-23 * * *'
  workflow_dispatch:

jobs:
  cl-job: #input./utils/pool/config.yaml
    name: Collecting 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: init
      run: | 
         npm install serve
         git config pull.rebase false
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    # - name: requirements.txt
      # run: pip install -r ./utils/pool/requirements.txt
    # - name: main.py
      # run: cd ./utils/pool/ && python main.py
    - name: requirements.txt
      run: pip install -r ./utils/clashcheck/requirements.txt
    - name: main.py
      run: cd ./utils/clashcheck/ && python main.py && python main.py && python main.py
    - run: ./.github/update-repo.sh || true   #output./utils/clashcheck/check.yaml
